name: SystemTest
on:
  workflow_call:

jobs:
  system-test:
    name: SystemTest
    runs-on:
      - self-hosted
      - k8s-api
      - linux-amd64-2-4096
      - burstable
      - linux-amd64-s

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: SystemTest
        id: build
        run: |
          echo "This is a SystemTest stage"
